# Fancy Indexing

Array의 element접근하는 방식이 여러가지가 있다.
- simple indexing
 + e.g., ``arr[0]``, ``Arr[1,2]`` 
 + C프로그램 등에서 사용하는 가장 기본적인 방법
- slices 
 + e.g., ``arr[:5]``
 + range를 통해 잘라내는 방법
- Boolean masks 
 + e.g., ``arr[arr > 0]``
 + 조건을 통해 골라내는 방법
 - *fancy indexing* 
 + simple indexing과 비슷하지만 scalar대신 index들의 array를 전달
 + 아래 예제들을 통해 살펴보자.

## Exploring Fancy Indexing


In [1]:
import numpy as np
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


index들의 1차원 array를 전달하자. 

In [3]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

주의) fancy indexing 결과의 shape는 바로  *index arrays*의 shape를 따른다. 즉,  참조하는 본래 *array*의 shape가 아니다.

In [4]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

Multi-dimension 경우를 살펴보자. 

In [5]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Simple indexing에서처럼 첫 번째, 두 번째 argument가 각각 row와 column을 가리킨다.

In [6]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

만약 argument들 사이에 shape가 일치하지 않으면 앞서 배운 broadcasting rule이 적용된다. 

In [7]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [11]:
row[:, np.newaxis] * col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

다시 한 번 강조하면 fancy indexing에 의한 결과값은 *broadcasted shape of the indices*를 따른다. 

## Combined Indexing

fancy indexing과 다른 indexing schemes이 같이 사용될 수 있다.

In [12]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


예) fancy indexing과 simple indexing의 결함

In [13]:
X[2, [2, 0, 1]]

array([10,  8,  9])

In [14]:
X[[2],[2,0,1]]

array([10,  8,  9])

예) fancy indexing과 slicing의 결함

In [15]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

예) fancy indexing과 masking의 결함

In [16]:
mask = np.array([1, 0, 1, 0], dtype=bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

## Modifying Values with Fancy Indexing

element 값에 대한 assignment가 (당연히) 가능하다.

In [18]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [19]:
x[i] -= 10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]
