# Aggregations: Min, Max, and Everything In Between

데이터에서 특징값이나 대표값을 계산하는 것은 매우 빈번하다.
 - 평균, 표준편차
 - 최소값, 최대값, 중간값, 분위값 등

NumPy는 그러한 계산을 위한 built-in  function들을 제공한다. 

## Summing the Values in an Array


In [0]:
import numpy as np

In [7]:
L = np.random.random(100)
sum(L)

55.507210877837814

NumPy 패키지의 ``sum`` 함수를 똑같이 사용할 수 있다.

In [8]:
np.sum(L)

55.50721087783783

그러나 NumPy version 이 훨씬 빠르다.

In [27]:
big_array = np.random.rand(10000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

1 loop, best of 3: 849 ms per loop
100 loops, best of 3: 7.44 ms per loop


## Minimum and Maximum

Python built-in function인 ``min``과  ``max``를 통해 최소값과 최대값을 구할 수 있다. 

In [28]:
min(big_array), max(big_array)

(1.322308113005377e-07, 0.9999999789224875)

마찬가지로 NumPy version이 존재하며 더 빠르다. 

In [29]:
np.min(big_array), np.max(big_array)

(1.322308113005377e-07, 0.9999999789224875)

In [30]:
%timeit min(big_array)
%timeit np.min(big_array)

1 loop, best of 3: 617 ms per loop
100 loops, best of 3: 7.99 ms per loop


Object method를 호출하는 형태도 가능하다.

In [31]:
print(big_array.min(), big_array.max(), big_array.sum())
%timeit big_array.min()

1.322308113005377e-07 0.9999999789224875 4998795.532906725
100 loops, best of 3: 7.94 ms per loop


### Multi dimensional aggregates

Muti-dimensional array에서도 가능하며, row 혹은 column 단위 적용에도 유용하다. 

In [32]:
M = np.random.random((3, 4))
print(M)

[[0.27961419 0.2876788  0.93856059 0.54466484]
 [0.03690037 0.29951128 0.04770504 0.45273079]
 [0.70787543 0.51268141 0.40778816 0.24904848]]


In [33]:
M.sum()

4.764759385904793

*axis* argument를 통해 축을 지정할 수 있다. 

In [34]:
M.min(axis=0)

array([0.03690037, 0.2876788 , 0.04770504, 0.24904848])

In [35]:
M.max(axis=1)

array([0.93856059, 0.45273079, 0.70787543])

In [41]:
X=np.random.random((3,4,5))
print(X)
print(X.min(axis=0))
print(X.min(axis=2))

[[[0.10321248 0.36406208 0.11625797 0.72840709 0.62064778]
  [0.57555845 0.75211788 0.97406748 0.71655905 0.40041203]
  [0.20006489 0.37535681 0.18780397 0.41908233 0.90223425]
  [0.85213831 0.22214794 0.64393842 0.51617981 0.50022024]]

 [[0.82501787 0.81677807 0.0276344  0.80778387 0.52404926]
  [0.88426163 0.26945154 0.16117094 0.36084004 0.53194196]
  [0.30088639 0.1956623  0.14576288 0.37187542 0.28805625]
  [0.35740227 0.11879351 0.85604978 0.45947571 0.32893543]]

 [[0.09335185 0.46931114 0.16836296 0.52615006 0.99297259]
  [0.19260904 0.35741807 0.85571933 0.5543251  0.11344926]
  [0.50728543 0.94534777 0.43893514 0.17669565 0.70258873]
  [0.02117942 0.48208561 0.22319139 0.60953641 0.0878563 ]]]
[[0.09335185 0.36406208 0.0276344  0.52615006 0.52404926]
 [0.19260904 0.26945154 0.16117094 0.36084004 0.11344926]
 [0.20006489 0.1956623  0.14576288 0.17669565 0.28805625]
 [0.02117942 0.11879351 0.22319139 0.45947571 0.0878563 ]]
[[0.10321248 0.40041203 0.18780397 0.22214794]
 [0.02

### Other aggregation functions


|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

